### ISSUE TITLE
Error when trying to use this plugin

### ISSUE THREAD

**Issue by LeaVerou** [tsung-ju/eleventy-plugin-mathjax#5]
Hi there,

Thanks for making this! I just tried to use it following exactly the instructions in the README and got this error when building:

```
[11ty] 1. Having trouble writing to "./blog/2023/11ty-indices/index.html" from "./blog/2023/11ty-indices/index.md" (via EleventyTemplateError)
[11ty] 2. Transform `mathjax` encountered an error when transforming ./blog/2023/11ty-indices/index.md. (via EleventyTransformError)
[11ty] 3. Can't find handler for document (via Error)
[11ty] 
[11ty] Original error stack trace: Error: Can't find handler for document
[11ty]     at HandlerList.handlesDocument (/Users/leaverou/Documents/lea.verou.me/node_modules/mathjax-full/js/core/HandlerList.js:60:15)
[11ty]     at HandlerList.document (/Users/leaverou/Documents/lea.verou.me/node_modules/mathjax-full/js/core/HandlerList.js:64:21)
[11ty]     at Object.document (/Users/leaverou/Documents/lea.verou.me/node_modules/mathjax-full/js/mathjax.js:11:41)
[11ty]     at Object.<anonymous> (/Users/leaverou/Documents/lea.verou.me/node_modules/eleventy-plugin-mathjax/.eleventy.js:57:26)
[11ty]     at Object.<anonymous> (/Users/leaverou/Documents/lea.verou.me/node_modules/@11ty/eleventy/src/BenchmarkGroup.js:32:26)
[11ty]     at Template.runTransforms (/Users/leaverou/Documents/lea.verou.me/node_modules/@11ty/eleventy/src/Template.js:514:30)
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11ty]     at async Template.renderPageEntry (/Users/leaverou/Documents/lea.verou.me/node_modules/@11ty/eleventy/src/Template.js:799:15)
[11ty]     at async /Users/leaverou/Documents/lea.verou.me/node_modules/@11ty/eleventy/src/Template.js:822:21
[11ty]     at async Promise.all (index 0)
[11ty] Benchmark   1655ms  38%  1684× (Configuration) "reading_time" Nunjucks Filter
[11ty] Wrote 0 files in 4.02 seconds (v2.0.1)
```

It’s not specific to that blog post, if I add that post to .eleventyignore it just complains about a different one.
From some googling, it appears that for some reason [a document handler is not registered](https://github.com/mathjax/MathJax-src/issues/265), though that's done on the plugin's side so it appears it's not something I could fix on my end.

**Comment by tsung-ju** [comment]
Hi, thanks for reporting the issue! I noticed that the error seems to be caused by MathJax being unable to parse your HTML due to syntax errors. For instance, changing the `</span>` to `</a>` in [this line](https://github.com/LeaVerou/lea.verou.me/blob/610f26d27cc5d4ec3e3f04c30af332ba2fae611f/_includes/page.njk#L130C2-L130C2) of your HTML template fixes the error for a majority of pages. However, there seems to be other syntax errors present.

If you only need LaTeX math in Markdown pages, I would recommend using [tani/markdown-it-mathjax3](https://github.com/tani/markdown-it-mathjax3) with `markdown-it` instead. It works directly on Markdown sources, so it shouldn't have issue with syntax errors in HTML.

**Comment by LeaVerou** [comment]
Wow, thanks for actually tracking it down, and for the markdown-it-mathjax3 recommendation!
